## Elena EDA

### Importing data file

In [1]:
import pandas as pd

df = pd.read_csv('US_counties_COVID19_health_weather_data.csv')

In [2]:
df

,date,county,state,fips,cases,deaths,stay_at_home_announced,stay_at_home_effective,lat,lon,...,min_temp_3d_avg,min_temp_5d_avg,min_temp_10d_avg,min_temp_15d_avg,dewpoint_3d_avg,dewpoint_5d_avg,dewpoint_10d_avg,dewpoint_15d_avg,date_stay_at_home_announced,date_stay_at_home_effective
0,2020-01-21,Snohomish,Washington,53061,1,0.0,no,no,48.047489,-121.697307,...,38.266667,38.92,38.44,36.146667,40.333333,41.64,40.74,37.973333,2020-03-23,2020-03-23
1,2020-01-22,Snohomish,Washington,53061,1,0.0,no,no,48.047489,-121.697307,...,39.233333,41.12,39.76,37.613333,42.633333,42.98,41.68,39.440000,2020-03-23,2020-03-23
2,2020-01-23,Snohomish,Washington,53061,1,0.0,no,no,48.047489,-121.697307,...,42.900000,41.74,41.15,38.226667,44.733333,43.72,42.47,40.120000,2020-03-23,2020-03-23
3,2020-01-24,Cook,Illinois,17031,1,0.0,no,no,41.840039,-87.816716,...,32.366667,30.02,27.43,24.886667,31.433333,28.50,25.00,22.693333,2020-03-20,2020-03-21
4,2020-01-24,Snohomish,Washington,53061,1,0.0,no,no,48.047489,-121.697307,...,44.600000,42.54,41.75,38.226667,46.000000,44.30,42.88,41.293333,2020-03-23,2020-03-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
790326,2020-12-04,Sweetwater,Wyoming,56037,2077,10.0,no,no,41.659538,-108.879567,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
790327,2020-12-04,Teton,Wyoming,56039,1724,2.0,no,no,43.934776,-110.589759,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
790328,2020-12-04,Uinta,Wyoming,56041,1175,5.0,no,no,41.287648,-110.547639,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
790329,2020-12-04,Washakie,Wyoming,56043,517,8.0,no,no,43.904970,-107.682819,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
790330,2020-12-04,Weston,Wyoming,56045,419,2.0,no,no,43.840417,-104.567663,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
for x in df.columns:
    print(x, df[x].isna().sum())

date 0
county 0
state 0
fips 163
cases 0
deaths 16655
stay_at_home_announced 0
stay_at_home_effective 0
lat 17835
lon 17835
total_population 17835
area_sqmi 17835
population_density_per_sqmi 17835
num_deaths 74408
years_of_potential_life_lost_rate 74408
percent_fair_or_poor_health 17835
average_number_of_physically_unhealthy_days 17835
average_number_of_mentally_unhealthy_days 17835
percent_low_birthweight 35382
percent_smokers 17835
percent_adults_with_obesity 17835
food_environment_index 22449
percent_physically_inactive 17835
percent_with_access_to_exercise_opportunities 18701
percent_excessive_drinking 17835
num_alcohol_impaired_driving_deaths 24107
num_driving_deaths 24107
percent_driving_deaths_with_alcohol_involvement 24107
num_chlamydia_cases 45401
chlamydia_rate 45401
teen_birth_rate 45172
num_uninsured 17835
percent_uninsured 17835
num_primary_care_physicians 51561
primary_care_physicians_rate 51047
num_dentists 38665
dentist_rate 38665
num_mental_health_providers 67855
mental_health_provider_rate 67855
preventable_hospitalization_rate 25000
percent_with_annual_mammogram 20804
percent_vaccinated 20649
high_school_graduation_rate 37113
num_some_college 17835
population 17835
percent_some_college 17835
num_unemployed_CHR 17835
labor_force 17835
percent_unemployed_CHR 17835
percent_children_in_poverty 17835
eightieth_percentile_income 18326
twentieth_percentile_income 18326
income_ratio 18326
num_single_parent_households_CHR 17853
num_households_CHR 17853
percent_single_parent_households_CHR 17853
num_associations 17835
social_association_rate 17835
annual_average_violent_crimes 61879
violent_crime_rate 61879
num_injury_deaths 33978
injury_death_rate 33978
average_daily_pm2_5 24632
presence_of_water_violation 28439
percent_severe_housing_problems 17835
severe_housing_cost_burden 17835
overcrowding 17835
inadequate_facilities 17835
percent_drive_alone_to_work 18090
num_workers_who_drive_alone 18090
percent_long_commute_drives_alone 18090
life_expectancy 29083
num_deaths_2 26804
age_adjusted_death_rate 26804
num_deaths_3 299236
child_mortality_rate 299236
num_deaths_4 462963
infant_mortality_rate 462963
percent_frequent_physical_distress 17835
percent_frequent_mental_distress 17835
percent_adults_with_diabetes 17835
num_hiv_cases 215528
hiv_prevalence_rate 215528
num_food_insecure 17835
percent_food_insecure 17835
num_limited_access 22449
percent_limited_access_to_healthy_foods 22449
num_drug_overdose_deaths 347038
drug_overdose_mortality_rate 347038
num_motor_vehicle_deaths 109543
motor_vehicle_mortality_rate 109543
percent_insufficient_sleep 17835
num_uninsured_2 17835
percent_uninsured_2 17835
num_uninsured_3 17835
percent_uninsured_3 17835
other_primary_care_provider_rate 22999
percent_disconnected_youth 435025
average_grade_performance 169680
average_grade_performance_2 178054
median_household_income 17835
percent_enrolled_in_free_or_reduced_lunch 48446
segregation_index 260344
segregation_index_2 87899
homicide_rate 457337
num_deaths_5 186307
suicide_rate_age_adjusted 186307
num_firearm_fatalities 222459
firearm_fatalities_rate 222459
juvenile_arrest_rate 257075
average_traffic_volume_per_meter_of_major_roadways 17835
num_homeowners 17835
percent_homeowners 17835
num_households_with_severe_cost_burden 18130
percent_severe_housing_cost_burden 18130
population_2 17835
percent_less_than_18_years_of_age 17835
percent_65_and_over 17835
num_black 17835
percent_black 17835
num_american_indian_alaska_native 17835
percent_american_indian_alaska_native 17835
num_asian 17835
percent_asian 17835
num_native_hawaiian_other_pacific_islander 17835
percent_native_hawaiian_other_pacific_islander 17835
num_hispanic 17835
percent_hispanic 17835
num_non_hispanic_white 17835
percent_non_hispanic_white 17835
num_not_proficient_in_english 17835
percent_not_proficient_in_english 17835
percent_female 17835
num_rural 18942
percent_rural 18942
num_housing_units 17835
num_households_CDC 17835
num_below_poverty 17835
num_unemployed_CDC 17835
per_capita_income 17835
num_no_highschool_diploma 17835
num_age_65_and_older 17835
num_age_17_and_younger 17835
num_disabled 17835
num_single_parent_households_CDC 17835
num_minorities 17835
num_limited_english_abilities 17835
num_multi_unit_housing 17835
num_mobile_homes 17835
num_overcrowding 17835
num_households_with_no_vehicle 17835
num_institutionalized_in_group_quarters 17835
percent_below_poverty 17835
percent_unemployed_CDC 17835
percent_no_highschool_diploma 17835
percent_age_65_and_older 17835
percent_age_17_and_younger 17835
percent_disabled 17835
percent_single_parent_households_CDC 17835
percent_minorities 17835
percent_limited_english_abilities 17835
percent_multi_unit_housing 17835
percent_mobile_homes 17835
percent_overcrowding 17835
percent_no_vehicle 17835
percent_institutionalized_in_group_quarters 17835
percentile_rank_below_poverty 17835
percentile_rank_unemployed 17835
percentile_rank_per_capita_income 17835
percentile_rank_no_highschool_diploma 17835
percentile_rank_socioeconomic_theme 17835
percentile_rank_age_65_and_older 17835
percentile_rank_age_17_and_younger 17835
percentile_rank_disabled 17835
percentile_rank_single_parent_households 17835
percentile_rank_household_comp_disability_theme 17835
percentile_rank_minorities 17835
percentile_rank_limited_english_abilities 17835
percentile_rank_minority_status_and_language_theme 17835
percentile_rank_multi_unit_housing 17835
percentile_rank_mobile_homes 17835
percentile_rank_overcrowding 17835
percentile_rank_no_vehicle 17835
percentile_rank_institutionalized_in_group_quarters 17835
percentile_rank_housing_and_transportation 17835
percentile_rank_social_vulnerability 17835
km_to_closest_station 17835
CALL 84360
ELEV_M 17835
station_id 34239
station_name 34239
mean_temp 34244
min_temp 34399
max_temp 35222
dewpoint 87536
sea_level_pressure 387426
station_pressure 134979
visibility 98906
wind_speed 69244
max_wind_speed 72664
wind_gust 333692
precipitation 106830
precip_flag 106830
fog 34239
rain 34239
snow 34239
hail 34239
thunder 34239
tornado 34239
mean_temp_3d_avg 37386
mean_temp_5d_avg 40528
mean_temp_10d_avg 49950
mean_temp_15d_avg 56238
max_temp_3d_avg 39981
max_temp_5d_avg 44651
max_temp_10d_avg 57517
max_temp_15d_avg 67038
min_temp_3d_avg 37729
min_temp_5d_avg 41042
min_temp_10d_avg 50849
min_temp_15d_avg 57491
dewpoint_3d_avg 91249
dewpoint_5d_avg 94835
dewpoint_10d_avg 104846
dewpoint_15d_avg 111689
date_stay_at_home_announced 151112
date_stay_at_home_effective 151112